- name: Apache | Certificates | SSL | Insert | {{ apache_crtdir }}
  copy:
    content: "{{ apache_ssl_key }}"
    dest: "{{ apache_crtdir }}/private/{{ apache_fqdn }}.key"
    group: "{{ apache_service_user }}"
    owner: "{{ apache_service_user }}"
    mode: 0440

- copy:
    content: "{{ apache_ssl_crt }}"
    dest: "{{ apache_crtdir}}/certs/{{ apache_fqdn }}.crt"
    group: "{{ apache_service_user }}"
    owner: "{{ apache_service_user }}"
    mode: 0444

- copy:
    content: "{{ apache_ssl_cabundle }}"
    dest: "{{ apache_crtdir }}/certs/{{ apache_fqdn }}.cabundle.crt"
    group: "{{ apache_service_user }}"
    owner: "{{ apache_service_user }}"
    mode: 0444

- name: Apache | Certificates | SSL | Configure
  lineinfile: dest={{ apache_sslconf }} regexp="^#?\s*({{ apache_certs.key }}\s*)" backrefs=yes  line="\\1 {{ apache_certs.value }}"
  with_items:
    - { key: 'SSLCertificateFile', value: "{{ apache_crtdir }}/certs/{{ apache_fqdn }}.crt" }
    - { key: 'SSLCertificateKeyFile', value: "{{ apache_crtdir }}/private/{{ apache_fqdn }}.key" }
    - { key: 'SSLCertificateChainFile', value: "{{ apache_crtdir}}/certs/{{ apache_fqdn }}.cabundle.crt" }
  notify: restart apache
  loop_control:
    loop_var: apache_certs

