galaxy_info:
  author: Sami Silén
  description: Apache 2.x for RedHat and Debian
  company: CSC - IT Center for Science
  license: license (BSD, MIT)

  min_ansible_version: 2.2

  platforms:
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - all

  galaxy_tags:
    - web
    - apache
