wildfly_user:       jboss         # OS User to run the server
wildfly_basedir:    /opt          # Directory to install the server
wildfly_home:       /opt/jboss    # Wildfly home dir
wildfly_version:    10.0.0.Final  # Software version
wildfly_admin:      admin         # Management console admin user
wildfly_password:   admin         # Management console admin password
jdk_version:        jdk1.8.0_131  # jdk version
