---

- name: Download JDK rpm
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"
    dest: /tmp/jdk.rpm
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"

- name: Install the downloaded jdk
  yum:
    name: /tmp/jdk.rpm
    state: present
  become: yes
